Read me
polinapechenkova/javascript_base pull request #1
Opened 2023-12-22 16:05 UTC by polinapechenkova

Привет! Проверьте, пожалуйста, учла предыдущие замечания.

2023-12-22 16:11 UTC, polinapechenkova commented
.

2023-12-24 19:58 UTC, Levitinn requested changes
я не вижу свои прошлые комментарии из за того что ты заново добавляешь файлы каждый раз. попробуй разобраться с гитом для начала, если не выйдет, пиши мне в дискорд. попробуем вместе ( но после того как попытаешься сама). потому что дальше будет очень тяжело проверять ДЗ не видя свои комментарии

2023-12-24 19:58 UTC, Levitinn commented on 5-languages
> +    default:
забыла прописать default

2023-12-25 13:56 UTC, polinapechenkova commented
Привет! Большое спасибо, кажется, несколько разобралась с git.  
Исправила default.

2023-12-29 08:39 UTC, Levitinn approved these changes
молодец)

2024-01-02 16:17 UTC, merged