Read me
polinapechenkova/javascript_base pull request #2
Opened 2024-01-05 22:56 UTC by polinapechenkova

Привет!  Надеюсь, отступы корректные.

2024-01-08 19:40 UTC, Levitinn requested changes

2024-01-08 19:40 UTC, Levitinn commented on 7-converter.js
по задаче требуется написать функцию, которая будет конвертировать валюты. твое решение понятно и закрывает задачу, однако, стоит понимать, что сейчас ты занесла в функцию "лишнюю" логику, а именно: сейчас она возвращает предложение, которое описывает курс. 
Если, например, тебе потребуется где нибудь переиспользовать эту логику ( конвертации) в другом месте, твоя функция не подойдет, так как помимо значения валюты она отдает целое предложение. Тебе придется написать еще одну функцию, которая делает то же самое. А это не есть хорошо. Поправь свою функцию таким образом, чтобы она отдавала только значение, а текст ты можешь дописать в консоль логе 
пример 
function convertCalculate(sum, changeCurrency, getCurrency) {
.......
}
console.log('Сумма после конвертации составит:' + convertCalculate(70000, "rub", "usd"));

2024-01-08 19:40 UTC, Levitinn commented on 7-converter.js
> +      const convertToEUR = sum / 102;
создавать переменные в case тебе так же, не понадобится, ведь ты можешь сразу возвращать значение 
`
case "usd":
      return sum / 92;
`

2024-01-08 19:40 UTC, Levitinn commented on 8-crypto.js
> +  switch (true) {
если условие одно или два, не нужно использовать switch case, стоит обойтись if else

2024-01-09 14:17 UTC, polinapechenkova commented
Привет! Внесла изменения.

2024-01-09 17:42 UTC, Levitinn approved these changes

2024-01-11 14:42 UTC, merged